"""Modified from train/midi-preprocess.py, discards duplicate MIDI files (i.e., keep only ones present in GigaMIDI but not in LMD)"""

import json
import traceback
from argparse import ArgumentParser
from concurrent.futures import ProcessPoolExecutor
from glob import glob

from tqdm import tqdm

from anticipation.convert import midi_to_compound
from anticipation.config import PREPROC_WORKERS

# generated by `check_md5_clash.py`
LMD_MD5_CLASH_METADATA_PATH = "/scratch/shared/datasets/gigamidi/gigamidi_lmd_md5_collisions.json"

GIGAMIDI_RAW_DATA_DIR = "/scratch/shared/datasets/gigamidi/raw_huggingface/"


def get_clash_md5s(clash_md5s_path):
    md5_clash_gigamidi_paths = [
        v["gigamidi_path"] for v in json.load(open(clash_md5s_path))
    ]

    return md5_clash_gigamidi_paths

def convert_midi(filename, md5_clash_gigamidi_paths, debug=False):
    if filename.split(GIGAMIDI_RAW_DATA_DIR)[-1] in md5_clash_gigamidi_paths:
        if debug:
            print("Skipping clashing MIDI file: ", filename)
        return 1
    
    try:
        tokens = midi_to_compound(filename, debug=debug)
    except Exception:
        if debug:
            print("Failed to process: ", filename)
            print(traceback.format_exc())

        return 1

    with open(f"{filename}.amt-compound.txt", "w") as f:
        f.write(" ".join(str(tok) for tok in tokens))

    return 0


def main(args):
    md5_clash_gigamidi_paths = get_clash_md5s(LMD_MD5_CLASH_METADATA_PATH)
    print(len(md5_clash_gigamidi_paths), "clashing MIDI files found")

    filenames = glob(args.dir + "/**/*.mid", recursive=True) + glob(
        args.dir + "/**/*.midi", recursive=True
    )

    print(f"Preprocessing {len(filenames)} files with {PREPROC_WORKERS} workers")
    with ProcessPoolExecutor(max_workers=PREPROC_WORKERS) as executor:
        results = list(
            tqdm(
                executor.map(convert_midi, filenames, [md5_clash_gigamidi_paths] * len(filenames)),
                desc="Preprocess",
                total=len(filenames),
            )
        )

    discards = round(100 * sum(results) / float(len(filenames)), 2)
    print(
        f"Successfully processed {len(filenames) - sum(results)} files (discarded {discards}%)"
    )


if __name__ == "__main__":
    parser = ArgumentParser(description="prepares a MIDI dataset")
    parser.add_argument("--dir", help="directory containing .mid files for training", default=GIGAMIDI_RAW_DATA_DIR)

    args = parser.parse_args()

    if args.dir != GIGAMIDI_RAW_DATA_DIR:
        GIGAMIDI_RAW_DATA_DIR = args.dir

    main(parser.parse_args())
